### PR TITLE
Add pending because of dependency statistic

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by mtds** [comment]
Just for the record, before deciding to accept this pull request, I will add a comment here in order to have a little bit of history and/or context to a possible change in the code base.

I understood from your pull request that you want to add an additional metric to the exporter, 
related to 'pending job over dependency X'. So, the modified 'squeue' command included in the
request adds an `'%r'` option which will output the reason why the job is in its current state. 

The patch is concerned to differentiate those jobs which are pending because interdependent
to other jobs completion and not because of lack of resources, priority issues, etc.

I am not sure about this addition. How many jobs are pending because of inter dependency
on your side? On our cluster, most of the time, an high percentage of jobs are waiting in the
queue for lack or oversubscribing of available resources. Of course, cluster utilization varies
greatly between sites.

Also, this pull request modify the README section related to compile this exporter on CentOS.
Most of the Golang dependencies are removed. Why? Did you try to compile the exporter on
recent version of CentOS and verify that not all those dependencies are needed?

**Comment by MatMaul** [comment]
@mtds thanks for the fast feedback :)
Jobs waiting for other dependency job to finish are quite high here, around 1/3 of all the pending jobs.

Regarding compiling: seems like they changed the semantic of go get then ?
With last go version it just doesn't work, you need to specify the underlying folder where your actual go package exists, it needs to match the import basically.
The one I removed are transient dependencies from github.com/prometheus/client_golang/prometheus that are automatically fetched, hence the removal.

**Comment by mtds** [comment]
Ok @MatMaul. It looks fine to me and your pull request is back compatible, so it should not break anything which is already used in production, whenever it will be decided to upgrade the exporter.

I just need another info: which version of Slurm are you using? This exporter was initially developed
with version 14.03, which is to be considered prehistoric considering the latest version of Slurm and
the fast pacing of the development.

@Golang: yes, you are right. The latest version of Go changed the 'go get' model and it's quite
some time since I have compiled the exporter on a CentOS node. I will eventually spin up a VM
later and check again. Which version of CentOS are you using?

**Comment by MatMaul** [comment]
v17.02 for us. On your 14.03 version if you can call squeue with %r I think we are fine.
I didn't do it with CentOS to be fair but with my Ubuntu.
Just tested on a RHEL 7.6 with official go package (1.9.4) and it works fine after setting up a GOPATH.

**Comment by mtds** [comment]
Yes, the ``%r`` works fine also on the old 14.03 version. I will merge your pull request into master, then. Thanks for having submitted it!

Regarding CentOS/RHEL: I will make a test later and eventually update again the README.

**Pull request merged**
